/// Flutter icons MyFlutterApp
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  MyFlutterApp
///      fonts:
///       - asset: fonts/MyFlutterApp.ttf
///
/// 
///
import 'package:flutter/widgets.dart';

class MyFlutterApp {
  MyFlutterApp._();

  static const _kFontFam = 'MyFlutterApp';
  static const String? _kFontPkg = null;

  static const IconData copy = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData credit_card = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData download = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData map_pin = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData navigation = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData repeat = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData user = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector__stroke_ = IconData(0xe808, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vector = IconData(0xe809, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData clock = IconData(0xe80a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
